apiVersion: v1
kind: Service
metadata:
  name: proxy
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-web-svc
      protocol: TCP
      name: http
  selector:
    tier: proxy
